In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
# Sentences
sent = [  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
#Vocabulary Size 
voc_size = 10000

In [5]:
# One Hot Representation
onehot_repr = [one_hot(words, voc_size) for words in sent]
print(onehot_repr)

[[7033, 7549, 1417, 9460], [7033, 7549, 1417, 3399], [7033, 5402, 1417, 1160], [2170, 9084, 5908, 7658, 3848], [2170, 9084, 5908, 7658, 8916], [3982, 7033, 8818, 1417, 6871], [8177, 3624, 9892, 7658]]


In [6]:
# Word Embedding Representation
# Importing Libraries
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential


In [7]:
import numpy as np

In [8]:
sent_length = 8
embedded_docs = pad_sequences(onehot_repr, maxlen = sent_length, padding='pre' )
print(embedded_docs)

[[   0    0    0    0 7033 7549 1417 9460]
 [   0    0    0    0 7033 7549 1417 3399]
 [   0    0    0    0 7033 5402 1417 1160]
 [   0    0    0 2170 9084 5908 7658 3848]
 [   0    0    0 2170 9084 5908 7658 8916]
 [   0    0    0 3982 7033 8818 1417 6871]
 [   0    0    0    0 8177 3624 9892 7658]]


In [9]:
dim = 10

In [10]:
model = Sequential()
model.add(Embedding(voc_size,10,input_length= sent_length))
model.compile('adam', 'mse')

In [11]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 8, 10)             100000    
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [12]:
print(model.predict(embedded_docs))

[[[-4.41881269e-03 -2.99484022e-02  3.55675332e-02  4.62961234e-02
    3.60955335e-02  1.24660954e-02 -4.26939391e-02  4.60926443e-03
    3.23373340e-02  2.31735818e-02]
  [-4.41881269e-03 -2.99484022e-02  3.55675332e-02  4.62961234e-02
    3.60955335e-02  1.24660954e-02 -4.26939391e-02  4.60926443e-03
    3.23373340e-02  2.31735818e-02]
  [-4.41881269e-03 -2.99484022e-02  3.55675332e-02  4.62961234e-02
    3.60955335e-02  1.24660954e-02 -4.26939391e-02  4.60926443e-03
    3.23373340e-02  2.31735818e-02]
  [-4.41881269e-03 -2.99484022e-02  3.55675332e-02  4.62961234e-02
    3.60955335e-02  1.24660954e-02 -4.26939391e-02  4.60926443e-03
    3.23373340e-02  2.31735818e-02]
  [-7.02702999e-03  2.51506902e-02  3.80983017e-02 -3.56829166e-03
    9.61748511e-03  1.88376345e-02  2.69730724e-02 -8.18002224e-03
    1.60115846e-02 -1.66199356e-03]
  [ 4.51027229e-03  4.72060107e-02  3.33252586e-02  3.54600586e-02
   -4.54247706e-02  1.50561333e-04  1.28643848e-02 -1.97362546e-02
   -2.57565267e-

In [14]:
embedded_docs[0]

array([   0,    0,    0,    0, 7033, 7549, 1417, 9460], dtype=int32)

In [16]:
print(model.predict(embedded_docs)[0])

[[-4.4188127e-03 -2.9948402e-02  3.5567533e-02  4.6296123e-02
   3.6095534e-02  1.2466095e-02 -4.2693939e-02  4.6092644e-03
   3.2337334e-02  2.3173582e-02]
 [-4.4188127e-03 -2.9948402e-02  3.5567533e-02  4.6296123e-02
   3.6095534e-02  1.2466095e-02 -4.2693939e-02  4.6092644e-03
   3.2337334e-02  2.3173582e-02]
 [-4.4188127e-03 -2.9948402e-02  3.5567533e-02  4.6296123e-02
   3.6095534e-02  1.2466095e-02 -4.2693939e-02  4.6092644e-03
   3.2337334e-02  2.3173582e-02]
 [-4.4188127e-03 -2.9948402e-02  3.5567533e-02  4.6296123e-02
   3.6095534e-02  1.2466095e-02 -4.2693939e-02  4.6092644e-03
   3.2337334e-02  2.3173582e-02]
 [-7.0270300e-03  2.5150690e-02  3.8098302e-02 -3.5682917e-03
   9.6174851e-03  1.8837634e-02  2.6973072e-02 -8.1800222e-03
   1.6011585e-02 -1.6619936e-03]
 [ 4.5102723e-03  4.7206011e-02  3.3325259e-02  3.5460059e-02
  -4.5424771e-02  1.5056133e-04  1.2864385e-02 -1.9736255e-02
  -2.5756527e-02 -4.1676473e-02]
 [-5.6456774e-05  4.0501628e-02  6.8994872e-03  9.6917748e